#!/bin/bash

if [ "$1" != "" ]; then
    cd ./server
    gcc -pthread newServer.c -o ns
    ./ns $1

    cd -
    cd ./irc-master/dist
    java -jar IRC-client.jar
else
    echo "podaj numer portu"
fi
